apiVersion: v1
kind: ConfigMap
metadata:
  name: gitsync-config
data:
  GIT_SYNC_REPO: "https://github.com/nitesh-kumar-sharma/airflow-dags"
  GIT_SYNC_BRANCH: "master"
  GIT_SYNC_ROOT: "/tmp/git"
  GIT_SYNC_DEPTH: "1"
  GIT_SYNC_ONE_TIME: "false"
  GIT_SYNC_WAIT: "30"
  GIT_KNOWN_HOSTS: "false"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-configmap
  labels:
    env: airflow-test
data:
  airflow.cfg: |
    [core]
    dags_folder = /usr/local/airflow/dags
    base_log_folder = /usr/local/airflow/logs
    logging_level = INFO
    executor = KubernetesExecutor
    parallelism = 32
    load_examples = False
    plugins_folder = /usr/local/airflow/plugins
    sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@airflow-metastore:5432/airflow

    [celery]
    broker_url =
    result_backend =

    [webserver]
    base_url = http://0.0.0.0:8080
    rbac=False
    web_server_host = 0.0.0.0
    web_server_port = 8080
    dag_default_view = tree

    [kubernetes]
    namespace = default
    airflow_configmap = airflow-configmap
    worker_service_account_name = default
    worker_container_image_pull_policy = IfNotPresent
    worker_dags_folder = /usr/local/airflow/dags
    worker_container_repository = nikush001/k8-airflow
    worker_container_tag = latest
    delete_worker_pods = false
    git_repo = https://github.com/nitesh-kumar-sharma/airflow-dags
    git_branch = master
    git_subpath = simple
    git_sync_credentials_secret = git-credentials
    git_sync_root = /tmp/git
    git_dags_folder_mount_point = /usr/local/airflow/dags
    git_sync_container_repository = nikush001/git-sync
    git_sync_container_tag = latest
    git_sync_init_container_name = git-sync-clone
    dags_volume_claim = airflow-dags
    in_cluster = True

    [kubernetes_secrets]
    SQL_ALCHEMY_CONN = airflow-secrets=sql_alchemy_conn

    [admin]
    # UI to hide sensitive variable fields when set to True
    hide_sensitive_variable_fields = True
