# postgres - airflow-metastore
# Definition : deployment, persistent storage, service

apiVersion: v1
kind: Service
metadata:
  name: airflow-metastore
  labels:
    app: postgres
  namespace: default
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: airflow-metastore

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
  labels:
    app: postgres
data:
  PG_DB: airflow
  PG_USER: airflow
  PG_PASS: airflow

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: default
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
  volumeName: postgres-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: default
  labels:
    app: postgres
spec:
  capacity:
    storage: 100Mi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/kuber/airflow-mounted-vol/postgres-data

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-metastore
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        name: airflow-metastore
    spec:
      containers:
        - name: airflow-metastore
          image: nikush001/postgres:11.7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: postgres-data
              mountPath: /usr/local/postgresql/data/pgdata
              subPath: pgdata
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data