apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  labels:
    env: airflow-test
type: Opaque
data:
  GIT_SYNC_USERNAME: bml0ZXNoLWt1bWFyLXNoYXJtYQ==
  GIT_SYNC_PASSWORD: ODUkTHVja3kzNiQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  labels:
    env: airflow-test
type: Opaque
data:
  sql_alchemy_conn: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FpcmZsb3c6YWlyZmxvd0BhaXJmbG93LW1ldGFzdG9yZTo1NDMyL2FpcmZsb3c=