# postgres - airflow-broker
# Definition : deployment, persistent storage, service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: airflow-broker
  template:
    metadata:
      labels:
        name: airflow-broker
    spec:
      containers:
        - name: airflow-broker
          image: nikush001/rabbitmq:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: broker-ui
              protocol: TCP
              containerPort: 15672
            - name: broker-queue
              protocol: TCP
              containerPort: 5672
---

apiVersion: v1
kind: Service
metadata:
  name: airflow-broker
spec:
  type: LoadBalancer
  ports:
    - name: broker-ui
      protocol: TCP
      port: 15672
      nodePort: 30010
    - name: broker-queue
      protocol: TCP
      port: 5672
      nodePort: 30011
  selector:
    name: airflow-broker