apiVersion: v1
kind: ConfigMap
metadata:
  name: gitsync-config
data:
  GIT_SYNC_REPO: "https://github.com/nitesh-kumar-sharma/airflow-dags"
  GIT_SYNC_BRANCH: "master"
  GIT_SYNC_ROOT: "/tmp/git"
  GIT_SYNC_DEST: "sync"
  GIT_SYNC_DEPTH: "1"
  GIT_SYNC_ONE_TIME: "false"
  GIT_SYNC_WAIT: "60"
  GIT_SYNC_USERNAME: "nitesh-kumar-sharma"
  GIT_KNOWN_HOSTS: "false"
  GIT_PASSWORD: "85$Lucky36$"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  labels:
    env: airflow-test
data:
  airflow.cfg: |
   [core]
   dags_folder = /usr/local/airflow/dags
   base_log_folder = /usr/local/airflow/logs
   logging_level = INFO
   executor = KubernetesExecutor
   parallelism = 32
   load_examples = False
   plugins_folder = /root/airflow/plugins
   sql_alchemy_conn = postgresql+psycopg2://airflow:airflow@airflow-metastore:5432/airflow

   [webserver]
   base_url = http://0.0.0.0:8080
   rbac=True
   web_server_host = 0.0.0.0
   web_server_port = 8080
   dag_default_view = tree

   [kubernetes]
   airflow_configmap = airflow-configmap
   worker_service_account_name = default
   worker_container_image_pull_policy = IfNotPresent
   worker_dags_folder = /usr/local/airflow/dags
   worker_container_repository = airflow
   delete_worker_pods = true
   git_repo = https://github.com/nitesh-kumar-sharma/airflow-dags
   git_branch = master
   git_subpath = simple
   git_user = nitesh-kumar-sharma
   git_password = 85$Lucky36$
   git_sync_root = /tmp/git
   git_dags_folder_mount_point = /usr/local/airflow/dags
   dags_volume_claim = airflow-dags
   in_cluster = True
   git_sync_container_repository = k8s.gcr.io/git-sync
   git_sync_container_tag = v3.0.1
   git_sync_init_container_name = git-sync-clone