apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags
  labels:
    env: airflow-test
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: dag-pv

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dag-pv
  labels:
    env: airflow-test
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /d/data/airflow/dags